### ISSUE TITLE
Notice 모델 변경 요청

### ISSUE THREAD

**Issue by yjyoon-dev** [kw-notice/kw-notice-dormitory#1]
## 요청 사항
기존 KW 알리미 도메인 상에서는 공지사항 모델에 `id` 값과 `url` 값이 필수적으로 요구됨.
따라서 아래와 같은 새로운 필드를 추가해주기 바람.
```
{
  id: Int,
  // . . .
  url: String
  // . . .
}
```
이때 `id`는 게시글 별 고유값을 의미하며,
`url`은 공공기숙사 홈페이지 특성 상 게시글 별 url 추출이 불가하므로
공공기숙사 홈페이지 루트 경로를 기본값으로 넣는 것으로 고려 중임.

추가 의견이 있다면 코멘트 바랍니다~

**Comment by Tianea2160** [comment]
@yjyoon-dev 기존에 id가 uuid로 이루어져있어서 url을 추가하는 것은 문제가 없는데 id가 int 형식으로 반환이 안되는데 어떻게 할까요? uuid도 괜찮으시면 그대로 보내드리고 아니라면 db 스키마를 수정해야합니다.

**Comment by yjyoon-dev** [comment]
@Tianea2160 
공지사항의 베이스 모델에서 `id` 값을 `Long` 형식으로 관리하고 있어서 정수 형으로 받아야 할 것 같습니다.

![image](https://user-images.githubusercontent.com/72238126/215630078-530250f0-14c5-46e2-87bd-4dc4f84c9fb6.png)
공공기숙사 사이트에서 위와 같은 글 번호를 가져올 수 있다면 베스트이고,
어렵다면 서버 쪽에서 임의로 Long 형식 ID를 부여해도 될 것 같습니다~

**Comment by Tianea2160** [comment]
넵 알겠습니다. 기숙사 공지사항 api에서 id를 별도로 제공해주고 있지 않기 때문에 서버에서 자체적으로 만들도록 하겠습니다.
