### ISSUE TITLE
refactor: AlarmController의 예외처리 코드 개선 요청

### ISSUE THREAD

**Issue by kim-sung-jee** [kw-notice/kw-notice-dormitory#8]
안녕하세요 프로젝트를 구경하던 와중에 
궁금한점이나 제안하고 싶은 의견이 생겨서 조심스럽게 이슈 남깁니다

https://github.com/kw-notice/kw-notice-dormitory/blob/master/api-server-mvc/src/main/kotlin/com/knet/dormitory/web/alarm/AlarmController.kt

SendMesssageRequest(dto)의 값을 검증하는 행동을 AlaramController가 하는게 괜찮은건지 궁금합니다.
저는 dto객체 자기자신이 필드에 들어갈 값을 검증하는게  더 유연한 설계 같아 보입니다.

@ RequestBody로 들어오는 객체(dto)는 Jackson2HttpMessageConverter가 
적절한 생성자나 setter를 찾고 없으면 default object mapper를 사용하는 것으로 알고 있습니다.

위와 연결되는 내용입니다.
![image](https://user-images.githubusercontent.com/85841791/216975707-00fbddbf-0e27-457a-90b6-4d6dba8616d7.png)

if(isValid(dto)) 로 nullCheck 한 것을

다시한번 !! 를 붙여서 null이 아님을 명시(?)하는것이 중복되는 행위라고 생각이듭니다.

따라서 다음과 같이 수정하면 어떨지 의견남깁니다
읽어주셔서 감사합니다

```kotlin
class SendMessageRequest(
    val title: String = throw IllegalStateException(" "),
    val body: String = throw IllegalStateException(" "),
    val topic: AlarmTopic = throw IllegalStateException(" ")
)
```

```kotlin
@PostMapping("/send")
    fun sendMessage(@RequestBody dto: SendMessageRequest): CommonResponse {
        alarmService.sendMessage(dto.title, dto.body, dto.topic)
        return CommonResponse(status = HttpStatus.OK, message = "알림이 성공적으로 보내졌습니다.")
    }
```

**Comment by Tianea2160** [comment]
적어주신 내용을 잘 읽어보았습니다. 
저도 중복되는 행위를 줄이는 것이 좋다는 의견에 대해서 동감하고 있습니다. 
적어주신 것과 같이 수정하는 것도 좋다고 생각합니다. 
하지만 spring validator와 같은 다른 방법도 같이 검토를 해보고 해당 부분을 수정하도록 하겠습니다.

**Comment by Tianea2160** [comment]
해당 내용 코드 개선 및 branch 연결을 위해서 재오픈 합니다.

**Comment by Tianea2160** [comment]
요청하신 부분에 대해서 코드 수정을 진행해보았는데 이야기 해주신 부분에 대해서 예상과 다르게 동작해서 그대로 적용하기 힘들것 같습니다.
우선 컨트롤러에서 dto를 받을 때 기본 생성자(어떤 값도 들어가지 않은 빈 생성자가 필요)를 만들고 그다음에 세터를 통해서 값을 넣는 것으로 확인되었습니다. 따라서 보내 주신 부분과 같이 진행하면 값을 넣어주었음에도 값이 없는 예외가 발생합니다.
따라서 어쩔 수 없이 null 값에 대한 처리를 2번 진행하는 식으로 수정했습니다.

**Comment by kim-sung-jee** [comment]
답변감사합니다 ..!
